xap/chromium fixed compilation ffmpeg 4.4.1
[29835/50454] CXX obj/media/filters/filters/audio_renderer_algorithm.o
I../../third_party/icu/source/i18n -I../../third_party/libaom/source/libaom -I../../third_party/dav1d/version -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -flto=thin -fsplit-lto-unit -fwhole-program-vtables --target=aarch64-linux-gnu -ffile-compilation-dir=. -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declara           ^
../../media/filters/ffmpeg_demuxer.cc:408:24: error: no matching function for call to 'av_packet_get_side_data'
    uint8_t* id_data = av_packet_get_side_data(
                       ^~~~~~~~~~~~~~~~~~~~~~~